USE [master]
GO

CREATE DATABASE [TestTransactionSystem]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestTransactionSystem', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER12\MSSQL\DATA\TestTransactionSystem.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'TestTransactionSystem_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER12\MSSQL\DATA\TestTransactionSystem_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [TestTransactionSystem] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestTransactionSystem].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TestTransactionSystem] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET ARITHABORT OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TestTransactionSystem] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TestTransactionSystem] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TestTransactionSystem] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TestTransactionSystem] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET RECOVERY FULL 
GO

ALTER DATABASE [TestTransactionSystem] SET  MULTI_USER 
GO

ALTER DATABASE [TestTransactionSystem] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TestTransactionSystem] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TestTransactionSystem] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TestTransactionSystem] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [TestTransactionSystem] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TestTransactionSystem] SET  READ_WRITE 
GO


